name: CI

on:
  push:
    paths:
      - '**.kt'
      - '**.kts'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew -PleaseExcludeBenchmarks allTests --stacktrace